version: "0.1.0.{build}-{branch}"

os: Visual Studio 2019

environment:
  global:
    PROJECT_NAME: doukutsu-rs
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
      target_name: win64
      job_name: windows-x64
#    - channel: stable
#      target: i686-pc-windows-msvc
#      target_name: win32
#      job_name: windows-x32

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup update
  - rustup default %channel%
  - rustc -vV
  - cargo -vV

cache:
  - '%USERPROFILE%\.cache\sccache -> Cargo.toml'
  - '%USERPROFILE%\.cargo -> Cargo.toml'
  - 'target -> Cargo.toml'

#test_script:
#  - cargo build --verbose --all
#  - cargo test --verbose --all --no-fail-fast

build_script:
  - set DRS_BUILD_VERSION_OVERRIDE=%APPVEYOR_BUILD_VERSION%
  - cargo build --release --bin doukutsu-rs
  - mkdir release
  - copy target\release\doukutsu-rs.exe release
  - cd release
  - appveyor DownloadFile https://github.com/doukutsu-rs/game-data/archive/master.zip -FileName ../game-data.zip
  - 7z x ../game-data.zip
  - rename game-data-master data
  - 7z a ../doukutsu-rs_%target_name%.zip *
  - appveyor PushArtifact ../doukutsu-rs_%target_name%.zip
